# Generated by Django 5.1.2 on 2024-10-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tree', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
