# Generated by Django 5.1.2 on 2024-10-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Генеральный директор', 'Генеральный директор'), ('Руководитель отдела', 'Руководитель отдела'), ('Менеджер', 'Менеджер'), ('Старший инженер', 'Старший инженер'), ('Инженер', 'Инженер')], max_length=255)),
                ('hire_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
